export const SEND_FORM_HIRE_US = 'SEND_FORM_HIRE_US';
export const SEND_FORM_WORK_HERE = 'SEND_FORM_WORK_HERE';

export const SUCCESS_FORM_SEND = 'SUCCESS_FORM_SEND';
export const FAIL_FORM_SEND = 'FAIL_FORM_SEND';
export const CLEAR_FORM_STATUSES = 'CLEAR_FORM_STATUSES';
