export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const CHANGE_FIRST_FETCH_DATA = 'CHANGE_FIRST_FETCH_DATA';

export const FETCH_SELLERS = 'FETCH_SELLERS';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';

export const TOGGLE_IN_FAVORITE = 'TOGGLE_IN_FAVORITE';

export const CHANGE_FAVORITE_LIST = 'CHANGE_FAVORITE_LIST';

export const CHANGE_IS_FETCH_DATA = 'CHANGE_IS_FETCH_DATA';
