export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const CHANGE_FIRST_FETCH_DATA = 'CHANGE_FIRST_FETCH_DATA';

export const FETCH_SELLERS = 'FETCH_SELLERS';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';

export const ADD_IN_FAVORITE = 'ADD_IN_FAVORITE';
